version: '3'
services:
    myproject-postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: portal
        volumes:
            - .postgres/data/:/var/lib/postgresql/data/
    myproject-redis:
        image: redis:alpine
        container_name: redis
        command: redis-server --requirepass redis
        ports:
            - 6379:6379
        volumes:
            - .redis/data:/var/lib/redis
            - ./redis.conf:/usr/local/etc/redis/redis.conf
